# Page settings

baseurl = "https://martingeorgiev.com/ivayla/"
languageCode = "en-us"
title = "Ivayla Atanasova's  Resume"
theme = "hugo_resume_orbit"
googleAnalytics = "UA-110491290-1"

# Do not build files for websites. Need them? Set to false
disableRSS = false
disableSitemap = false
disable404 = false

[params]

# Meta
    description = "Ivayla Atanasova's profesional resume"
    author = "Martin Georgiev"

# Theme styles

    # The original template comes with 6 colour schemes. You may choose styles below.
    # "styles.css", "styles-2.css", "styles-3.css", "styles-4.css", "styles-5.css", "styles-6.css"
    # are available. Also the source LESS files are included so
    # it’s quick and easy to change the styling and colour scheme.

    styles = "styles.css"

# Sidebar sections

    # Profile section
    [params.profile]
        name = "Ivayla Atanasova"
        tagline = "Segnior Service Deivery Manager"
        avatar = "profile.png"

    # Contact section
    [params.contact]
        enable = true

        [[params.contact.list]]
        class = "email"
        icon = "fa-envelope"
        url = "mailto: ivayla.ivanova@gmail.com"
        title = "ivayla.ivanova@gmail.com"

        [[params.contact.list]]
        class = "phone"
        icon = "fa-phone"
        url = "tel:+359 885 307101"
        title = "+359 885 307101"

        [[params.contact.list]]
        class = "website"
        icon = "fa-globe"
        url = "//portfoliosite.com"
        title = "portfoliosite.com"

        [[params.contact.list]]
        class = "linkedin"
        icon = "fa-linkedin"
        url = "//linkedin.com/in/johndoe"
        title = "linkedin.com/in/johndoe"

        [[params.contact.list]]
        class = "github"
        icon = "fa-github"
        url = "//github.com/username"
        title = "github.com/username"

        [[params.contact.list]]
        class = "twitter"
        icon = "fa-twitter"
        url = "//twitter.com/username"
        title = "@twittername"

    # Education section
    [params.education]
        enable = true
        title = "Education"

        [[params.education.list]]
        degree = "MSc in Management in Telecommunications"
        college = "New Bulgarian University"
        dates = "2010 - Present"

        [[params.education.list]]
        degree = "BSc in Communication technique and technology"
        college = "Technical University"
        dates = "2005 - 2009"

    # Languages section
    [params.language]
        enable = true
        title = "Languages"

        [[params.language.list]]
        language = "Bulgarian"
        level = "Native"

        [[params.language.list]]
        language = "English"
        level = "Professional"

    # Interests section
    [params.interests]
        enable = true
        title = "Interests"

        [[params.interests.list]]
        interest = "Climbing"

        [[params.interests.list]]
        interest = "Snowboarding"

        [[params.interests.list]]
        interest = "Cooking"

        # QR section
    [params.qrcode]
        enable = true
        title = "QR Code"
        lastName = "Atanasova"
        firstName = "Ivayla"
        address = "Sofia, Bulgaria"
        phone = "+359885307101"
        email = "ivayla.ivanova@gmail.com"
        url = "martingeorgiev.com/ivayla/"
        note = "Service Delivery Manager"

# Main body sections

    # You may use markdown in summary, details and intro fields. But don't overdose, it's resume!:)

    # Summary section
    [params.summary]
        enable = true
        icon = "fa-user"
        title = "Career Profile"
        summary = "Dynamic and motivated professional with a proven record of building relationships, operating in high value projects. Experience of 10+ years into IT and telecommunication business environment. Passionate about process excellence, service integration and transformations and customers’ satisfaction."

    # Experiences section
    [params.experiences]
        enable = true
        icon = "fa-briefcase"
        title = "Experiences"

        [[params.jobs.list]]
        position = "Manager Enterprise Service Delivery"
        dates = "2013 – 2019"
        company = "GTT Communications, Inc. (Formerly Interoute Ltd)"
        details = "Acting as Senior Service Delivery Manager for the enterprise teams (20-30 people) operating on the UK market. I was providing leadership and taking responsibility for teams performances and development in dynamic and fast- paced environments. I was senior point of escalations for customers, as well as for third party companies/ vendors. Being on this position I was responsible for the end to end service delivery processes from quoting stage to final turn up of the services. Follow the acquisition I was deeply involved and strongly contributed to the integration and post- integration phase as: mapping existing delivery processes; driving process excellence in front of the customer and to the organization; Conduct post-implementation reviews to evaluate benefits accrued from new processes and system, as well as identifying the potential risks."
        tasks = [
            "Managed and maintained relationships with the customers via clear communication process;",
            "Managed and maintained relationships with the external vendors and partners;",
            "Worked with senior engineering management and project director to ensure process is followed and negotiating any areas, where improvement is needed;",
            "Responsible for all types of Documentations: Processes; Vendors; Roles and responsibilities;",
            "Responsible for: meeting the monthly targets, in terms of the planned financial forecast",
            "Preparing yearly; mid- yearly reviews; reviewing and approving merits for the team members and Delivery managers"
            ]
        more = "" 


        [[params.jobs.list]]
        position = "Account Process Manager"
        dates = "2009 - 2013"
        company = "Hewlett-Packard Global Delivery Bulgaria Center EOOD"
        details = "As account process manager for change management process I had to ensure that projects/change initiatives meet objectives on time and on budget.  I’ve worked into cross- functional teams’ environment, where I did apply a structured methodology and lead change management activities. I was acting as a coach for senior tower leaders and executives in helping them fulfill the role of change sponsor. Another important focus and responsibility, which I had was to provide input, document requirements and support the design and delivery of training programs."
        tasks = [
            "Responsible for monthly/ weekly reporting stats and trends;",
            "Chaired the regular CAB (Change Advisory Board) meeting;",
            "Managed stakeholders;",
            "Track and report issues;",
            "Define and measure success metrics and monitor change progress;",
            "Support change management at the organizational level;",
            "Manage the change portfolio"
            ]
        
        [[params.jobs.list]]
        position = "Application administrator/ Trainee"
        dates = "2008 - 2009"
        company = "Mobiltel EAD"
        details = "Starting as a trainee in the Enterprise Operations Division. Then acting as application admin supporting the company`s CRM system based on ITIL fundamentals. Participating in the implementation of different ITIL modules: change, incident, problem management."
        tasks = [
            "Preparing system`s/tool`s SLAs`",
            "Analyzing KPI`s reporting",
            "Maintain ongoing documentations"
            ]

    # Projects section
    [params.projects]
        enable = false
        icon = "fa-archive"
        title = "Projects"
        intro = "**You can list your side projects or open source libraries in this section.** Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum et ligula in nunc bibendum fringilla a eu lectus"

        [[params.projects.list]]
        title = "Hugrid"
        url = "https://github.com/aerohub/hugrid"
        tagline = "Grid theme for Hugo. It's a kind of boilerplate to perform anyone or anything quickly. Portfolio, collection, bookmarks, contacts and so on"

        [[params.projects.list]]
        title = "Simple FAQ Theme for Hugo"
        url = "https://github.com/aerohub/hugo-faq-theme"
        tagline = "Simple FAQ Theme for Hugo. You may use this theme for building very simple FAQs or note lists."

        [[params.projects.list]]
        title = "Hugo Identity"
        url = "https://github.com/aerohub/hugo-identity-theme"
        tagline = "Little profile/card-style template for Hugo."

        [[params.projects.list]]
        title = "Orbit"
        url = "https://github.com/aerohub/hugo-orbit-theme"
        tagline = "Hugo Resume/CV Theme for Developers."

        [[params.projects.list]]
        title = "Me"
        url = "https://github.com/aerohub/hugo-me-theme"
        tagline = "A simple responsive Hugo theme for personal site."

    # Skills section
    [params.skills]
        enable = true
        icon = "fa-rocket"
        title = "Skills & Proficiency"

        [[params.skills.list]]
        skill = "Project management"
        level = "98%"
                
        [[params.skills.list]]
        skill = "Customers communication"
        level = "98%"

        [[params.skills.list]]
        skill = "Process Excellence"
        level = "95%"

        [[params.skills.list]]
        skill = "Integrations"
        level = "95%"

        [[params.skills.list]]
        skill = "Transitions"
        level = "75%"

        [[params.skills.list]]
        skill = "Agile"
        level = "60%"

        [[params.skills.list]]
        skill = "ITIL"
        level = "60%"

        [[params.skills.list]]
        skill = "SLA"
        level = "60%"

        [[params.skills.list]]
        skill = "KPI"
        level = "60%"

        [[params.skills.list]]
        skill = "Service Delivery"
        level = "60%"

        [[params.skills.list]]
        skill = "Telecommunication services and products"
        level = "60%"

        [[params.skills.list]]
        skill = "Diversity- ability to understand and integrate diverse opinions"
        level = "60%"

        [[params.skills.list]]
        skill = "Diplomacy"
        level = "60%"

        [[params.skills.list]]
        skill = "Basic Network knowledge"
        level = "60%"


    # Skills section
    [params.certificates]
        enable = true
        icon = "fa-rocket"
        title = "Certificates"

        [[params.certificates.list]]
        certificate = "Scrum Master Practitioner"
        type = "Training"
        date = "2019"
                
        [[params.certificates.list]]
        certificate = "Agile PM Foundation"
        type = "Certified"
        date = "2018"

        [[params.certificates.list]]
        certificate = "Prince2 Practitioner"
        type = "Training"
        date = "2015"

        [[params.certificates.list]]
        certificate = "Prince2 Foundation"
        type = "Certified"
        date = "2014"

        [[params.certificates.list]]
        certificate = "ITIL: Release, Control and Validation"
        type = "Certified"
        date = "2013"

        [[params.certificates.list]]
        certificate = "ITIL Foundation V3"
        type = "Certified"
        date = "2010"

        [[params.certificates.list]]
        certificate = "Customer Service Management3"
        type = "Training"
        date = "2013"

    # Footer section

    # The original template is released under the Creative Commons Attribution 3.0 License.
    # Please keep the original attribution link when using for your own project.
    # If you'd like to use the template without the attribution,
    # you can check out other license options via template author's website: themes.3rdwavemedia.com
    # 
    # As for Hugo port you may rewrite the "Ported for..." line with setting your name below.

    [params.footer]
        copyright = "Martin Georgiev"
