# This workflow will build and deploy the static website.
#
# To use this workflow, you will need to set up a .github/ci.yml
# file with configuration. 

name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Update theme
        # (Optional)If you have the theme added as submodule, you can pull it and use the most updated version
        run: git submodule update --init --recursive

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Build
        # remove --minify tag if you do not need it
        # docs: https://gohugo.io/hugo-pipes/minification/
        # working-directory: scripts
        run: hugo --config ./martingeorgiev/config.toml --themesDir ../.. --destination ./martingeorgiev/public

      - name: Azure Container registry login
        uses: azure/docker-login@v1
        with:
            login-server: martingeorgiev.azurecr.io
            username: ${{ secrets.ACR_USERNAME }}
            password: ${{ secrets.ACR_PASSWORD }}

      # - name: Build the Docker image
      #   run: |
      #     docker build . --file ./Dockerfile --tag martingeorgiev.azurecr.io/martingeorgievinfo:latest
      #     docker push martingeorgiev.azurecr.io/martingeorgievinfo:latest
      #     docker build . --file ./Dockerfile --tag martingeorgiev.azurecr.io/martingeorgievinfo:$(date +'%Y.%m.%d').${{ github.run_number }}
      #     docker push martingeorgiev.azurecr.io/martingeorgievinfo:$(date +'%Y.%m.%d').${{ github.run_number }}
      
      # - name: Azure login
      #   uses: azure/login@v1
      #   with:
      #       creds: ${{ secrets.AZURE_CREDENTIALS }}

  #     - name: Delete old files from blob storage
  #       uses: azure/CLI@v1
  #       with:
  # #        azcliversion: 2.30.0
  #         inlineScript: |
  #             az storage blob delete-batch --source '$web' --account-name martingeorgievinfo
              
  #     - name: Upload to blob storage
  #       uses: azure/CLI@v1
  #       with:
  # #        azcliversion: 2.30.0
  #         inlineScript: |
  #             az storage blob upload-batch --account-name martingeorgievinfo -d '$web' -s .
  #     - name: Purge CDN endpoint
  #       uses: azure/CLI@v1
  #       with:
  # #        azcliversion: 2.30.0
  #         inlineScript: |
  #           az cdn endpoint purge --content-paths  "/*" --profile-name martingeorgievinfo --name martingeorgievinfo --resource-group martingeorgievinfo
  #   # Azure logout 
  #     - name: logout
  #       run: |
  #             az logout
  #       if: always()
